---
- name: -> Download Check_mk Server
  action: command wget http://mathias-kettner.com/download/{{ check_mk_version }}.tar.gz -O /usr/src/{{ check_mk_version }}.tar.gz creates=/usr/src/{{ check_mk_version }}.tar.gz
  tags:
  - get_check-mk_tar.gz
  - check-mk_server

- name: Unarchive Check_mk Server
  action: unarchive src=/usr/src/{{ check_mk_version }}.tar.gz dest=/usr/src copy=no
  tags:
  - unarchive_check-mk_tar.gz
  - check-mk_server

- name: Setup Check_mk Server
  shell: ./setup.sh --yes 
  args:
    chdir: /usr/src/{{ check_mk_version }}
  tags:
  - check-mk_server

- name: Patch mail Script to find pnp4nagios
  action: replace dest=/usr/share/check_mk/notifications/mail 
    regexp="^        path = context.get"
    replace='        path = "/usr/share/pnp4nagios/html/index.php"'  
  tags:
  - patch_check-mk_server

- name: -> Download Check_mk Agent
  action: get_url url=http://mathias-kettner.com/download/{{ item }} 
    dest=/etc/ansible/roles/check_mk/files/debian/
  with_items: deb_packages
  tags:
  - get_check-mk_agent
  - check-mk_agent
  delegate_to: localhost

- name: upload Agent packages
  action: synchronize src=/etc/ansible/roles/check_mk/files/debian/{{ item }}
    dest=/tmp/
    archive=no
    checksum=yes
  with_items: deb_packages
  tags: 
  - install_check-mk_agent
  - check-mk_agent

- name: -> install Agent on Monitoring Host
  action: command dpkg -i -E --force-confdef /tmp/{{ item }}
  with_items: deb_packages
  tags:
  - install_check-mk_agent
  - check-mk_agent  